
name: Subir a s3

on:
  push:
    branches: [ "main" ]

jobs:
  subir-archivo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: CamiloBaeza/test@master
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_acces_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{secrets.AWS_BUCKET}}
          source_dir: './archivo_ejemplo_01.py'
          destination_dir: 's3://tarroloco/python files/'
 